### ISSUE TITLE
Broken LaTex rendering

### ISSUE THREAD

**Issue by andylolu2** [kierandidi/sde-course#1]
![image](https://github.com/kierandidi/sde-course/assets/66584117/aa6ffb98-d4c9-4579-ae37-70be0853c7d6)

Hi, I'm taking the course but the web page appears to be a bit broken. Tried on both Firefox and Chrome.

**Comment by kierandidi** [comment]
Hey, thanks for the issue! You are on the wrong webpage (it is the older version of it). I fixed the Latex rendering in the new one which should be the URL I gave in the lecture: sde-course.netlify.app. I also added the link now in the README of this repo so you can directly go to the page there. Hope that works, let me know if there are still any issues!

**Comment by andylolu2** [comment]
Thanks! Somehow I managed to guess a different valid URL 😅
